### ISSUE TITLE
**User Input Vector Spike**

### ISSUE THREAD

**Issue by emilyastranova** [tyleraharrison/wikiDataProject#14]
- [ ] Parse user input into a vector of strings (words separated by spaces)
- [ ] Loop through entire map of wikiEntries checking if match with search term

**Comment by ZacheryM** [comment]
Solution implemented on Zach branch, waiting review. @tyleraharrison

**Comment by emilyastranova** [comment]
Need to address user input not matching uppercase/lowercase using toLower() @ZacheryM
